---
title: "AnnieEDA"
author: "Annie Shapiro"
date: "5/29/2018"
output: html_document
---

#filter out 2016/2017
```{r}
library(dplyr)
bees <- read.csv("~/Desktop/Math345/345-Final-Project/vHoneyNeonic_v02.csv")

bees <- bees %>% filter(year != 2016 & year!= 2017 & state != "HI")

```

```{r}
i <- numeric

for (i in 1:727){
  if(bees$nTHIAMETHOXAM[i]==0){
    bees$nTHIAMETHOXAM[i] <- bees$nTHIAMETHOXAM[i] + 1}
  if(bees$nCLOTHIANIDIN[i]==0){
    bees$nCLOTHIANIDIN[i] <- bees$nCLOTHIANIDIN[i] + 1}
  if(bees$nIMIDACLOPRID[i]==0){
    bees$nIMIDACLOPRID[i] <- bees$nIMIDACLOPRID[i] + 1}
  if(bees$nACETAMIPRID[i]==0){
    bees$nACETAMIPRID[i] <- bees$nACETAMIPRID[i] + 1}
  if(bees$nTHIACLOPRID[i]==0){
    bees$nTHIACLOPRID[i] <- bees$nTHIACLOPRID[i] + 1}
}

bees$stocks <- bees$stocks/1000
bees <- bees %>% mutate(yrsince1998 = year - 1998)

write.csv(bees, file = "bees.csv")

```

##num colonies by each pesticide
```{r}
library(ggplot2)

ggplot(bees, aes(x=log(nCLOTHIANIDIN), y=log(numcol))) + geom_point(aes(color=year)) #not sure what to make of this

ggplot(bees, aes(x=log(nIMIDACLOPRID), y=log(numcol))) + geom_point(aes(color=year)) #more defined neg cor, num of IMID increases by year

ggplot(bees, aes(x=log(nTHIAMETHOXAM), y=log(numcol))) + geom_point(aes(color=year)) #slight  neg cor, num of THIA increases by year

ggplot(bees, aes(x=log(nACETAMIPRID), y=log(numcol))) + geom_point(aes(color=year)) #slight neg cor, num of ACET increases by year, didn't really exist till later

ggplot(bees, aes(x=log(nTHIACLOPRID), y=log(numcol))) + geom_point(aes(color=year)) #VERY slight neg cor, some clumps 

ggplot(bees, aes(x=log(nAllNeonic), y=log(numcol))) + geom_point(aes(color=year)) #neg cor, striations by year 

##SUGGESTS YEAR NEEDS RANDOM INT BUT NOT SLOPE??

```

##yield by each pesticide
```{r}
library(ggplot2)

ggplot(bees, aes(x=log(nCLOTHIANIDIN), y=yieldpercol)) + geom_point(aes(color=year)) #neg cor

ggplot(bees, aes(x=log(nIMIDACLOPRID), y=yieldpercol)) + geom_point(aes(color=year)) #VERY slight cor 

ggplot(bees, aes(x=log(nTHIAMETHOXAM), y=yieldpercol)) + geom_point(aes(color=year)) #neg cor, clear striations by year

ggplot(bees, aes(x=log(nACETAMIPRID), y=yieldpercol)) + geom_point(aes(color=year)) #slight neg cor

ggplot(bees, aes(x=log(nTHIACLOPRID), y=yieldpercol)) + geom_point(aes(color=year)) #VERY slight neg cor, doesnt seem too frequently used

ggplot(bees, aes(x=log(nAllNeonic), y=yieldpercol)) + geom_point(aes(color=year)) #slight neg cor, striations by year 

##SUGGESTS YEAR NEEDS RANDOM INT BUT NOT SLOPE??

```

##price factors
```{r}
#STOCKS
ggplot(bees, aes(x=log(numcol), y=log(stocks))) + geom_point(aes(color=year)) #clear pos cor

ggplot(bees, aes(x=yieldpercol, y=log(stocks))) + geom_point(aes(color=year)) # pos cor, less clear

ggplot(bees, aes(x=log(numcol), y=log(stocks))) + geom_point(aes(color=Region)) #south and northeast have fewer cols, stocks less in south 

ggplot(bees, aes(x=yieldpercol, y=log(stocks))) + geom_point(aes(color=Region)) # stocks higher in W, lower in S

#PRICE PER LB

ggplot(bees, aes(x=log(numcol), y=priceperlb)) + geom_point(aes(color=year)) #strange shape, clear striations by year, expected relationship

ggplot(bees, aes(x=yieldpercol, y=priceperlb)) + geom_point(aes(color=year)) # VERY SLIGHT neg cor, clear striations

ggplot(bees, aes(x=log(numcol), y=priceperlb)) + geom_point(aes(color=Region)) #less clear trends, south has less cols? no strong relation between price and region seen here

ggplot(bees, aes(x=yieldpercol, y=priceperlb)) + geom_point(aes(color=Region)) # no clear trends
```

#looking at region vars
```{r}
ggplot(bees, aes(x=Region, y=numcol)) + geom_boxplot() #lot of var in midwest, fair amount in west, NE has low number of cols

ggplot(bees, aes(x=Region, y=yieldpercol)) + geom_boxplot() #Midwest and South have greater yield on avg

ggplot(bees, aes(x=Region, y=totalprod)) + geom_boxplot() #more var in midwest

ggplot(bees, aes(x=Region, y=priceperlb)) + geom_boxplot() #pretty even across region

ggplot(bees, aes(x=Region, y=nAllNeonic)) + geom_boxplot() #midwest uses more and has large var

ggplot(bees, aes(x=Region, y=nCLOTHIANIDIN)) + geom_boxplot() #midwest uses more and has large var

ggplot(bees, aes(x=Region, y=nIMIDACLOPRID)) + geom_boxplot() #all but NE pretty even, west has high var

ggplot(bees, aes(x=Region, y=nTHIAMETHOXAM)) + geom_boxplot() #MW large var, followed by S. very little in NE, W

ggplot(bees, aes(x=Region, y=nACETAMIPRID)) + geom_boxplot() #low in all states, lots of var in W

ggplot(bees, aes(x=Region, y=nTHIACLOPRID)) + geom_boxplot() #lots of var across all regions, esp. NE

```

```{r}
library(tidyr)
bees_wide <- spread(bees, key=year, value=yieldpercol)
ggplot(bees, aes(x = year, y = yieldpercol, color = state)) + geom_line() + theme(legend.position = "none") + stat_smooth(method = "loess", se = FALSE)
```

#MODELING
```{r}
library(lme4)


#unconditional means
uncondmean <- lmer(yieldpercol ~ 1 + (1|state), data = bees)
summary(uncondmean) # 59.556 mean yield across all states across all years, 146.2 within state dev between individual yields and the state mean across all years, 200 between state dev


#unconditional growth
uncondgrow <- lmer(yieldpercol ~ yrsince1998 + (yrsince1998|state), data = bees)
summary(uncondgrow) #67.6229 mean yield in 1998, -0.974 mean yearly change in yield, 98.9023 var within state, 0.6787 var between states in rates of change in yield during the observation period, 314.0613 var btw states in 1998 

uncondgrow2 <- lmer(yieldpercol ~ yrsince1998 + (1|state), data = bees)
L1 <- logLik(uncondgrow)
L0 <- logLik(uncondgrow2)
D <- 2*(L1-L0)
.5*(1-pchisq(D, 2)) + .5*(1-pchisq(D,1)) #do need random slope
```


```{r}
lmer1 <- lmer(yieldpercol ~ yrsince1998 + (log(priceperlb) + log(nCLOTHIANIDIN) + log(nIMIDACLOPRID) + log(nTHIAMETHOXAM) + log(nACETAMIPRID) + log(nTHIACLOPRID))*log(stocks) + log(priceperlb):log(nCLOTHIANIDIN) + log(priceperlb):log(nTHIAMETHOXAM) + log(priceperlb):log(nACETAMIPRID)+ log(priceperlb):log(nTHIACLOPRID)+ log(nIMIDACLOPRID):log(nCLOTHIANIDIN) + log(nTHIAMETHOXAM):log(nIMIDACLOPRID) + log(nTHIAMETHOXAM):log(nACETAMIPRID) + log(nTHIACLOPRID):log(nCLOTHIANIDIN)+ log(nTHIACLOPRID):log(nIMIDACLOPRID) + log(nTHIACLOPRID):log(nTHIAMETHOXAM) + log(nTHIACLOPRID):log(nACETAMIPRID)+ (yrsince1998|state), data=bees)
summary(lmer1)

#take out unnecessary interactions
lmer2 <- lmer(yieldpercol ~ yrsince1998 + log(nCLOTHIANIDIN) + log(nIMIDACLOPRID) + log(nACETAMIPRID) + log(nTHIAMETHOXAM) + (log(priceperlb) +log(nTHIACLOPRID))*log(stocks) + log(priceperlb)+  log(nIMIDACLOPRID):log(nCLOTHIANIDIN) + log(nTHIAMETHOXAM):log(nIMIDACLOPRID) + log(nTHIAMETHOXAM):log(nACETAMIPRID) + log(nTHIACLOPRID):log(nCLOTHIANIDIN)+ log(nTHIACLOPRID):log(nIMIDACLOPRID) + log(nTHIACLOPRID):log(nTHIAMETHOXAM) + log(nTHIACLOPRID):log(nACETAMIPRID)+ (yrsince1998|state), data=bees)


lmer1.1 <- update(lmer1, REML=F)
lmer2.1 <- update(lmer2, REML=F)

D<-2*(logLik(lmer1.1) - logLik(lmer2.1))
1-pchisq(D,8) # p=0.468, prefer smaller


lmer3 <- lmer(yieldpercol ~ yrsince1998 + log(nCLOTHIANIDIN) + log(nIMIDACLOPRID) + log(nACETAMIPRID) + log(nTHIAMETHOXAM) + log(nTHIACLOPRID) +log(priceperlb)*log(stocks) + log(priceperlb) + (yrsince1998|state), data=bees)
lmer3.1 <- update(lmer3, REML=F)

D<-2*(logLik(lmer2.1) - logLik(lmer3.1))
1-pchisq(D,8) #p=0.6, prefer smaller

summary(lmer3)

lmer4 <- lmer(yieldpercol ~ yrsince1998  + log(nTHIAMETHOXAM)  +log(priceperlb)*log(stocks) + log(priceperlb) + (yrsince1998|state), data=bees)
lmer4.1 <- update(lmer4, REML=F)
anova(lmer3.1, lmer4.1) # p=0.26, prefer smaller

summary(lmer4)

lmer5 <- lmer(yieldpercol ~ yrsince1998 +log(priceperlb)*log(stocks) + log(priceperlb) + (yrsince1998|state), data=bees)
lmer5.1 <- update(lmer5, REML=F)
anova(lmer4.1, lmer3.1) # p=0.26, prefer smaller

summary(lmer5)
```


#total colonies as Y value

```{r}
#unconditional means
uncondmean2 <- lmer(log(numcol) ~ 1 + (1|state), data = bees)
summary(uncondmean2) # 10.1515 log(?) mean yield across all states across all years, 0.04478 within state dev between individual yields and the state mean across all years, 1.61446 between state dev


#unconditional growth
uncondgrow <- lmer(log(numcol) ~ yrsince1998 + (yrsince1998|state), data = bees)
summary(uncondgrow) #10.245020 mean yield in 1998, -0.014659 mean yearly change in yield, 0.021531 var within state, 0.001189 var between states in rates of change in yield during the observation period, 1.473287 var btw states in 1998 

uncondgrow2 <- lmer(log(numcol) ~ yrsince1998 + (1|state), data = bees)
L1 <- logLik(uncondgrow)
L0 <- logLik(uncondgrow2)
D <- 2*(L1-L0)
.5*(1-pchisq(D, 2)) + .5*(1-pchisq(D,1)) #do need random slope
```


```{r}
numcol1 <- lmer(log(numcol) ~ (yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN) + log(nIMIDACLOPRID) + log(nTHIAMETHOXAM)+ log(nACETAMIPRID)+ log(nTHIACLOPRID))^2 +(yrsince1998|state), data=bees)

summary(numcol1)

numcol2 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN) + log(nIMIDACLOPRID) + log(nTHIAMETHOXAM) + log(nACETAMIPRID) + log(nTHIACLOPRID) + yrsince1998:log(totalprod) + yrsince1998:log(stocks) + yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nTHIAMETHOXAM) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nTHIAMETHOXAM) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees)

numcol1.1 <- update(numcol1, REML=F)
numcol2.1 <- update(numcol2, REML=F)

anova(numcol2.1, numcol1.1) #prefer smaller

summary(numcol2)

numcol3 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN) + log(nTHIAMETHOXAM) + log(nACETAMIPRID) + log(nTHIACLOPRID) + yrsince1998:log(totalprod) + yrsince1998:log(stocks) + yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nTHIAMETHOXAM) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nTHIAMETHOXAM) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees, REML = F)

anova(numcol3, numcol2.1) #prefer smaller
summary(numcol3)

numcol3 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN) + log(nTHIAMETHOXAM) + log(nACETAMIPRID) + log(nTHIACLOPRID) + yrsince1998:log(totalprod) + yrsince1998:log(stocks) + yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nTHIAMETHOXAM) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nTHIAMETHOXAM) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees, REML = F)


numcol4 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN)  + log(nACETAMIPRID) + log(nTHIACLOPRID) + yrsince1998:log(totalprod) + yrsince1998:log(stocks) + yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees, REML = F)
anova(numcol4, numcol3) #p=0.03


numcol5 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN)  + log(nACETAMIPRID) + log(nTHIACLOPRID) +  yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees, REML = F)

anova(numcol5, numcol3) #p=0.002

numcol6 <- lmer(log(numcol) ~ yrsince1998 + log(totalprod) + log(stocks)+ log(priceperlb) + log(nCLOTHIANIDIN)  + log(nACETAMIPRID) + log(nTHIACLOPRID) +  yrsince1998:log(priceperlb) + yrsince1998:log(nACETAMIPRID) + yrsince1998:log(nTHIACLOPRID) + log(totalprod):log(stocks) + log(totalprod):log(priceperlb) + log(totalprod):log(nCLOTHIANIDIN) + log(totalprod):log(nACETAMIPRID) + log(totalprod):log(nTHIACLOPRID) + log(stocks):log(priceperlb) + log(stocks):log(nCLOTHIANIDIN) + log(stocks):log(nACETAMIPRID) + log(stocks):log(nTHIACLOPRID) + log(priceperlb):log(nACETAMIPRID) + log(priceperlb):log(nTHIACLOPRID) + (yrsince1998|state), data=bees, REML = F)



```

##DIAGNOSTICS MODEL 3
```{r}
library(HLMdiag)

conditionalResids<-HLMresid(numcol3, level = 1, standardize = T)
plot(fitted(numcol3), conditionalResids)
abline(h=0)
#not constant var


#b
marginalResids <- HLMresid(lmer3, level = "marginal", standardize = T)
plot(fitted(lmer3), marginalResids) # outliers
which(marginalResids < -2) #all but 1 low levels of nTHIAC

#c
cd <- cooks.distance(lmer5)
plot(cd, type= "h")

dotplot_diag(cd, cutoff = "internal", name = "cooks.distance")
which(cd > 0.02)
bees[c(545, 546, 553, 556), ] #SD and SC 2001 2002 only used 2 pesticides

#d
lev <- leverage(lmer.6, level=1)

dotplot_diag(lev[,1], cutoff = "internal", name = "leverage")


```